/**
 * CSS Class Names
 *
 * Centralized CSS class names used across all views.
 * Eliminates hardcoded class string literals scattered in templates.
 *
 * Usage:
 *   import { CLS } from '../constants';
 *   el('div', { className: CLS.CARD_GRID })
 */
export const CLS = {
  // Layout
  CARD_GRID: 'qi-card-grid',
  STAT_CARD: 'qi-stat-card',
  STAT_VALUE: 'qi-stat-value',
  STAT_LABEL: 'qi-stat-label',
  LIST: 'qi-list',
  LIST_ITEM: 'qi-item',
  LIST_ITEM_EXPANDED: 'qi-item expanded',
  ITEM_HEADER: 'qi-item-header',
  MSG: 'qi-msg',
  META: 'qi-meta',
  CODE_BLOCK: 'qi-code-block',
  CODE_HEADER: 'qi-code-header',
  CODE_CONTENT: 'qi-code-content',
  CODE_PRE: 'qi-code-pre',

  // Badges
  BADGE: 'qi-badge',
  CLASS_NAME: 'qi-class-name',
  EXPAND_ICON: 'qi-expand-icon',
  RULE: 'qi-rule',
  METHOD: 'qi-method',
  LINE: 'qi-line',

  // Explorer
  EXPLORER_LAYOUT: 'explorer-layout',
  EXPLORER_TREE: 'explorer-tree',
  TREE_HEADER: 'tree-header',
  TREE_VIEW_TOGGLES: 'tree-view-toggles',
  VIEW_TOGGLE: 'view-toggle',
  VIEW_TOGGLE_ACTIVE: 'view-toggle active',
  TREE_SEARCH: 'tree-search',
  TREE_CONTENT: 'tree-content',
  EXPLORER_MAIN: 'explorer-main',
  VIEWER_TABS: 'viewer-tabs',
  VIEWER_TAB: 'vtab',
  VIEWER_TAB_ACTIVE: 'vtab active',
  VIEWER_PANELS: 'viewer-panels',
  PANEL: 'vpanel',
  PANEL_ACTIVE: 'vpanel active',
  EXPLORER_CONTEXT: 'explorer-context',
  CONTEXT_HEADER: 'ctx-header',
  CONTEXT_BODY: 'ctx-body',

  // Tree / Package
  PKG_GROUP: 'pkg-group',
  PKG_SUMMARY: 'pkg-summary',
  PKG_ICON: 'pkg-ico',
  PKG_NAME: 'pkg-nm',
  PKG_COUNT: 'pkg-ct',
  PKG_BODY: 'pkg-body',
  CLASS_GROUP: 'cls-group',
  CLASS_SUMMARY: 'cls-summary',
  CLASS_ICON: 'cls-ico',
  CLASS_NAME_TAG: 'cls-nm',
  CLASS_KIND: 'cls-kind',
  CLASS_BODY: 'cls-body',
  METHOD_ITEM: 'mtd-item',
  METHOD_NAME: 'mtd-nm',
  METHOD_BADGE: 'mtd-badge',
  METHOD_BADGE_PUB: 'mtd-badge pub',
  METHOD_BADGE_ST: 'mtd-badge st',

  // Welcome / Dashboard
  WELCOME: 'welcome',
  WELCOME_TITLE: 'welcome-title',
  WELCOME_SUB: 'welcome-sub',
  STATS_ROW: 'stats-row',
  STAT: 'stat',
  STAT_VALUE_SHORT: 'stat-v',
  STAT_LABEL_SHORT: 'stat-l',
  LAYERS_SECTION: 'layers-section',
  LAYERS_GRID: 'layers-grid',
  LAYER_CARD: 'layer-card',
  LAYER_ICON: 'layer-ico',
  LAYER_NAME: 'layer-nm',
  LAYER_COUNT: 'layer-ct',
  QUALITY_GATE: 'qgate',
  QUALITY_GATE_PASS: 'qgate pass',
  QUALITY_GATE_FAIL: 'qgate fail',

  // Quick Access
  QUICK_ACCESS: 'quick-access',
  QA_SECTION: 'qa-section',
  QA_ITEM: 'qa-item',

  // UML
  UML_WRAP: 'uml-wrap',
  UML_HEADER: 'uml-hdr',
  UML_TITLE: 'uml-title',
  UML_KIND: 'uml-kind',
  UML_BODY: 'uml-body',
  UML_PRE: 'uml-pre',

  // Code View
  CODE_VIEW: 'code-view',
  CODE_HEADER_BAR: 'code-hdr',
  CODE_BUTTON: 'code-btn',
  CODE_BODY: 'code-body',
  CODE_NUMBERS: 'code-nums',
  CODE_LINE_NUMBER: 'lnum',
  CODE_LINE: 'cline',
  CODE_KEYWORD: 'code-keyword',
  CODE_TYPE: 'code-type',
  CODE_COMMENT: 'code-comment',
  CODE_STRING: 'code-string',

  // Context Panel
  CONTEXT_SECTION: 'ctx-section',
  CONTEXT_STATS: 'ctx-stats',
  CONTEXT_STAT: 'ctx-st',
  QUALITY_LIST: 'q-list',
  QUALITY_ITEM: 'q-item',
  METHOD_SIGNATURE: 'mtd-sig',
  METHOD_MODIFIERS: 'mtd-mods',
  CALL_LIST: 'call-list',
  CALL_ITEM: 'call-item',
  CALL_CLASS: 'call-cls',
  CALL_METHOD: 'call-mtd',
  CALL_LINE: 'call-line',

  // Empty State
  EMPTY_STATE: 'empty-state',
  EMPTY_ICON: 'empty-state-icon',
  EMPTY_TITLE: 'empty-state-title',
  EMPTY_DESC: 'empty-state-desc',
  EMPTY_CENTER: 'empty',
  EMPTY_ICON_SIMPLE: 'empty-icon',

  // Metrics
  METRICS_CARD_GRID: 'metrics-card-grid',
  METRICS_STAT_CARD: 'metrics-stat-card',
  METRICS_STAT_ICON: 'metrics-stat-icon',
  METRICS_STAT_VALUE: 'metrics-stat-value',
  METRICS_STAT_LABEL: 'metrics-stat-label',
  METRICS_CHART: 'metrics-chart',
  METRICS_CHART_TITLE: 'metrics-chart-title',
  METRICS_CHART_CONTAINER: 'metrics-chart-container',

  // AI Review
  AI_REVIEW_CONTAINER: 'ai-review-container',
  AI_STATS_GRID: 'ai-stats-grid',
  AI_STAT_CARD: 'ai-stat-card',
  AI_STAT_ICON: 'ai-stat-icon',
  AI_STAT_VALUE: 'ai-stat-value',
  AI_STAT_LABEL: 'ai-stat-label',
  AI_FILTER_BAR: 'ai-filter-bar',
  AI_FILTER_GROUP: 'ai-filter-group',
  AI_FILTER_BTN: 'ai-filter-btn',
  AI_TOGGLE_FILTERED: 'ai-toggle-filtered',
  AI_ISSUE_LIST: 'ai-issue-list',
  AI_ISSUE_ITEM: 'ai-issue-item',
  AI_ISSUE_HEADER: 'ai-issue-header',
  AI_ISSUE_META: 'ai-issue-meta',
  AI_SEVERITY_DOT: 'ai-severity-dot',
  AI_SOURCE_BADGE: 'ai-source-badge',
  AI_SEVERITY_TEXT: 'ai-severity-text',
  AI_EXPAND_ICON: 'ai-expand-icon',
  AI_ISSUE_MESSAGE: 'ai-issue-message',
  AI_ISSUE_FILE: 'ai-issue-file',
  AI_FILE_PATH: 'ai-file-path',
  AI_LINE_NUM: 'ai-line-num',
  AI_ISSUE_EXPANDED: 'ai-issue-expanded',
  AI_SUGGESTION_BLOCK: 'ai-suggestion-block',
  AI_SUGGESTION_HEADER: 'ai-suggestion-header',
  AI_SUGGESTION_TEXT: 'ai-suggestion-text',
  AI_REASONING_BLOCK: 'ai-reasoning-block',
  AI_REASONING_HEADER: 'ai-reasoning-header',
  AI_REASONING_TEXT: 'ai-reasoning-text',
  AI_CODE_BLOCK: 'ai-code-block',
  AI_CODE_HEADER: 'ai-code-header',
  AI_COPY_CODE_BTN: 'ai-copy-code-btn',
  AI_CODE_CONTENT: 'ai-code-content',
  AI_CONFIDENCE_BAR_WRAP: 'ai-confidence-bar-wrap',
  AI_CONFIDENCE_LABEL: 'ai-confidence-label',
  AI_CONFIDENCE_BAR_TRACK: 'ai-confidence-bar-track',
  AI_CONFIDENCE_BAR_FILL: 'ai-confidence-bar-fill',
  AI_STATIC_META: 'ai-static-meta',
  AI_CONFIDENCE_BADGE: 'ai-confidence-badge',
  AI_ENGINE_BADGE: 'ai-engine-badge',
  AI_MODEL_TAG: 'ai-model-tag',

  // Common
  HIDDEN: 'hidden',
  ACTIVE: 'active',
} as const;
