/**
 * Text constants - all hardcoded labels/messages extracted here
 */

export const TEXT = {
  // ========== Navigation Tabs (index.html) ==========
  TAB_EXPLORER: '📄 源码浏览器',
  TAB_GRAPH: '🔗 依赖图',
  TAB_RELATIONS: '🔀 跨文件关系',
  TAB_QUALITY: '⚠️ 质量分析',
  TAB_FRONTEND_QUALITY: '🔬 前端质量',
  TAB_METRICS: '📊 代码指标',
  TAB_ASSETS: '📂 项目资产',

  // ========== Stat Labels (index.html) ==========
  STAT_COMPONENTS: '组件总数',
  STAT_ISSUES: '质量风险',
  STAT_LOC: '代码行数',
  STAT_COMPLEXITY: '平均复杂度',

  // ========== Loading / Empty States ==========
  LOADING: '正在解析项目资产...',
  LOADING_FAILED: '加载失败: {message}',
  SEARCH_PLACEHOLDER: '🔍 搜索类或方法...',

  // ========== Code Explorer ==========
  EXPLORER_PACKAGE_VIEW: '📦 包视图',
  EXPLORER_LIST_VIEW: '📄 列表视图',
  EXPLORER_SEARCH_PLACEHOLDER: '🔍 搜索...',
  EXPLORER_TAB_DIAGRAM: '📐 类图',
  EXPLORER_TAB_SOURCE: '💻 源码',
  EXPLORER_TAB_CALLS: '🔗 调用',
  EXPLORER_DETAIL_HEADER: '📋 详情',
  EXPLORER_SELECT_PROMPT: '选择类或方法<br>查看详情',
  EXPLORER_SELECT_SOURCE_PROMPT: '选择方法查看源码',
  EXPLORER_SELECT_CALLS_PROMPT: '选择方法查看调用关系',
  EXPLORER_WELCOME_SUB: '{count} 个类 · {modules}',
  EXPLORER_SINGLE_MODULE: '单模块',
  EXPLORER_MODULES: '{count} 个模块',
  EXPLORER_STAT_CLASSES: '类',
  EXPLORER_STAT_METHODS: '方法',
  EXPLORER_STAT_ISSUES: '问题',
  EXPLORER_PROJECT_STRUCTURE: '📊 项目结构 ({typeName})',
  EXPLORER_LAYER_CLASSES: '{count} 个类',
  EXPLORER_QUALITY_PASS: '✅ 质量门禁通过',
  EXPLORER_QUALITY_FAIL: '❌ 质量门禁未通过',
  EXPLORER_COPY: '📋 复制',
  EXPLORER_OVERVIEW: '📊 概览',
  EXPLORER_METHODS: '方法',
  EXPLORER_FIELDS: '字段',
  EXPLORER_ISSUES: '⚠️ 问题 ({count})',
  EXPLORER_NO_ISSUES: '✅ 无质量问题',
  EXPLORER_CALLS: '🔗 调用 ({count})',
  EXPLORER_NO_SOURCE: '// No source for {methodName}',
  EXPLORER_MOD_PUB: 'pub',
  EXPLORER_MOD_ST: 'st',

  // ========== Component Explorer ==========
  COMPONENT_TITLE: '📦 项目组件 ({count})',
  COMPONENT_NOT_FOUND: '⚠️ 未找到组件',
  COMPONENT_BACK: '← 返回',
  COMPONENT_DESCRIPTION: '📝 描述',
  COMPONENT_FIELDS: '📊 字段 ({count})',
  COMPONENT_METHODS: '⚙️ 方法 ({count})',
  COMPONENT_MOD_PUBLIC: 'public',
  COMPONENT_MOD_STATIC: 'static',
  COMPONENT_METHOD_COUNT: '⚙️ {count} 方法',

  // ========== API Endpoint ==========
  API_EMPTY_TITLE: '暂无 API 端点数据',
  API_EMPTY_DESC: '当前项目未检测到 Spring API 端点。',
  API_EMPTY_REASON_1: '项目未使用 Spring Boot 框架',
  API_EMPTY_REASON_2: '未使用 @RestController / @Controller 注解',
  API_EMPTY_REASON_3: '数据文件是早期版本，未包含 Spring 分析',
  API_EMPTY_SUGGEST: '确保项目是 Spring Boot 项目，使用最新版分析工具重新分析。',
  API_STAT_LABEL: 'API 端点',
  API_STAT_BEANS: 'Spring Beans',
  API_STAT_BEAN_DEPS: 'Bean 依赖',
  API_FILTER_ALL: '全部 ({count})',
  API_HEADER: '📋 API 端点 ({count})',
  API_ENDPOINTS_COUNT: '{count} 个端点',
  API_PARAMS: '参数:',
  API_NO_MATCH: '无匹配的端点',

  // ========== Architecture Layer ==========
  ARCH_EMPTY_TITLE: '暂无架构分层数据',
  ARCH_EMPTY_DESC: '当前数据文件未包含架构分层分析结果。',
  ARCH_SUGGEST: '使用最新版本的 Java 分析工具重新分析项目。',
  ARCH_CAN_DO_1: '自动识别 Controller / Service / Repository / Entity 层',
  ARCH_CAN_DO_2: '显示层间依赖关系矩阵',
  ARCH_CAN_DO_3: '检测架构违规（如 Controller 直接调用 Repository）',
  ARCH_VIOLATIONS: '架构违规',
  ARCH_SOURCE_TARGET: '源层 → 目标层',
  ARCH_NO_VIOLATIONS_TITLE: '✅ 无架构违规',
  ARCH_NO_VIOLATIONS_MSG: '恭喜！未检测到架构分层违规。',
  ARCH_VIOLATIONS_HEADER: '⚠️ 架构违规 ({count})',
  ARCH_VIOLATION_TYPE: '类型:',
  ARCH_LAYER_GRAPH_TITLE: '🔀 层间依赖关系',

  // ========== Cross-File Relations ==========
  RELATIONS_EMPTY_TITLE: '暂无跨文件关系数据',
  RELATIONS_EMPTY_DESC: '当前项目未包含跨文件关系分析结果。请使用 Java 分析工具的完整分析模式重新扫描，以获取 Java 文件与 XML、SQL、配置文件等的关联关系。',
  RELATIONS_TOTAL: '总关系数',
  RELATIONS_TYPE_COUNT: '关系类型数',
  RELATIONS_TYPE_LABEL: '关系类型',
  RELATIONS_FILTER_ALL: '全部 ({count} 种类型)',
  RELATIONS_FILTERED_EMPTY_TITLE: '所有关系已过滤',
  RELATIONS_FILTERED_EMPTY_DESC: '当前没有符合所选过滤器的关系。',
  RELATIONS_LIST_HEADER: '📋 关系列表 ({count})',
  RELATIONS_COL_SOURCE_FILE: '源文件',
  RELATIONS_COL_SOURCE_ASSET: '源资产',
  RELATIONS_COL_TARGET_ASSET: '目标资产',
  RELATIONS_COL_TYPE: '关系类型',
  RELATIONS_COL_CONFIDENCE: '置信度',
  RELATIONS_COL_EVIDENCE: '证据',
  RELATIONS_SHOWING: '显示前 100 条，共 {total} 条关系',
  RELATIONS_UNKNOWN: 'Unknown',

  // ========== Force Graph ==========
  GRAPH_JDK_LIB: 'JDK 库',
  GRAPH_THIRD_PARTY: '第三方库',
  GRAPH_KIND_INTERFACE: '接口',
  GRAPH_KIND_ABSTRACT: '抽象类',
  GRAPH_KIND_ENUM: '枚举',
  GRAPH_KIND_CLASS: '类',
  GRAPH_NO_DESC: '暂无描述',
  GRAPH_STAT_METHODS: '📊 {count} 方法',
  GRAPH_STAT_FIELDS: '📝 {count} 字段',
  GRAPH_STAT_DEPS: '🔗 {count} 依赖',
  GRAPH_SEV_CRITICAL: '{count} 严重',
  GRAPH_SEV_MAJOR: '{count} 重要',
  GRAPH_SEV_MINOR: '{count} 提示',
  GRAPH_SEV_OK: '✅ 无问题',
  GRAPH_EDGE_IMPORT: '📦 Import 依赖关系',
  GRAPH_EDGE_REF: '引用该类的数量',

  // ========== Metrics Dashboard ==========
  METRICS_EMPTY_TITLE: '暂无代码指标数据',
  METRICS_EMPTY_DESC: '当前数据文件未包含代码指标分析结果。',
  METRICS_EMPTY_SUGGEST: '使用最新版本的 Java 分析工具重新分析项目，即可获取 LOC、复杂度、耦合度、内聚度等详细指标。',
  METRICS_TOTAL_CLASSES: '总类数',
  METRICS_TOTAL_METHODS: '总方法数',
  METRICS_TOTAL_LOC: '代码行数',
  METRICS_COMMENT_RATIO: '注释率',
  METRICS_AVG_COMPLEXITY: '平均复杂度',
  METRICS_COHESION: '内聚指数',
  METRICS_COMPLEXITY_TITLE: '📈 复杂度分布',
  METRICS_DISTRIBUTION_TITLE: '📊 类类型分布',
  METRICS_X_AVG_COMPLEXITY: '平均复杂度',
  METRICS_X_MAX_COMPLEXITY: '最大复杂度',
  METRICS_X_AVG_INHERITANCE: '平均继承深度',
  METRICS_X_MAX_INHERITANCE: '最大继承深度',
  METRICS_X_AVG_METHOD_LENGTH: '平均方法长度',
  METRICS_LEGEND_INTERFACE: '🔵 接口',
  METRICS_LEGEND_ABSTRACT: '🟣 抽象类',
  METRICS_LEGEND_CLASS: '🟢 实现类',
  METRICS_LEGEND_ENUM: '🟠 枚举',
  METRICS_LEGEND_UTILITY: '⚪️ 普通类',
  METRICS_PIE_NAME: '类类型',

  // ========== Project Assets ==========
  ASSETS_EMPTY_TITLE: '暂无项目资产数据',
  ASSETS_EMPTY_DESC: '当前项目未包含非 Java 文件资产信息。请使用 Java 分析工具的完整分析模式重新扫描，以获取 XML、YAML、SQL、Dockerfile 等配置文件详情。',
  ASSETS_TOTAL: '总资产数',
  ASSETS_TYPE_COUNT: '资产类型数',
  ASSETS_COUNT_LABEL: '{count} 项',
  ASSETS_UNKNOWN: 'Unknown',
  ASSETS_GROUP: 'Group:',
  ASSETS_VERSION: 'Version:',
  ASSETS_DEPS: '依赖数:',
  ASSETS_MIDDLEWARE: '中间件:',
  ASSETS_NAMESPACE: 'Namespace:',
  ASSETS_TABLES: '表数:',
  ASSETS_JAR: 'JAR:',
  ASSETS_TYPE_MAVEN: 'Maven POM',
  ASSETS_TYPE_YAML: 'YAML 配置',
  ASSETS_TYPE_PROPERTIES: 'Properties 配置',
  ASSETS_TYPE_SQL: 'SQL 脚本',
  ASSETS_TYPE_MYBATIS: 'MyBatis Mapper',
  ASSETS_TYPE_DOCKERFILE: 'Dockerfile',
  ASSETS_TYPE_DOCKER_COMPOSE: 'Docker Compose',
  ASSETS_TYPE_SHELL: 'Shell 脚本',
  ASSETS_TYPE_LOG: '日志配置',
  ASSETS_TYPE_MARKDOWN: 'Markdown 文档',
  ASSETS_TYPE_MODULES: '模块',
  ASSETS_TYPE_SCAN_SUMMARY: '扫描摘要',
  ASSETS_TYPE_ERRORS: '错误',

  // ========== Quality Dashboard ==========
  QUALITY_EMPTY_TITLE: '暂无质量分析数据',
  QUALITY_EMPTY_SUGGEST: '使用最新版 Java 分析工具重新分析项目。',
  QUALITY_TOTAL: '总问题数',
  QUALITY_FILTER_ALL: '全部',
  QUALITY_FILTER_CRITICAL: '严重',
  QUALITY_FILTER_MAJOR: '重要',
  QUALITY_FILTER_MINOR: '次要',
  QUALITY_FILTER_INFO: '信息',
  QUALITY_NO_ISSUES: '当前筛选条件下无问题',
  QUALITY_SOURCE_NOT_FOUND: '// Source not found for {name}',
  QUALITY_NO_SOURCE: '// No source code for {name}',
  QUALITY_LANG: 'Java',
  QUALITY_UNKNOWN_CLASS: 'Unknown',
  QUALITY_CODE_HEADER: '📄 {name} ()',

  // ========== Frontend Quality ==========
  FQ_CLI_CMD: 'cd frontend-quality-analyzer && node dist/cli.js --sourceRoot /path/to/project',

  // ========== Inspector Panel (ClassInspectorPanel) ==========
  INSPECTOR_LOADING: 'Loading...',
  INSPECTOR_NO_CODE: '暂无源码',
  INSPECTOR_NO_CODE_FALLBACK: '无代码',
  INSPECTOR_TAB_INFO: '📋 信息',
  INSPECTOR_TAB_SOURCE: '📄 源码',
  INSPECTOR_TYPE_LABEL: '类型',
  INSPECTOR_DESC_LABEL: '描述',
  INSPECTOR_FIELDS_LABEL: '字段',
  INSPECTOR_UNKNOWN: 'Unknown',

  // ========== Generic ==========
  UNKNOWN: 'Unknown',
  FALLBACK_ICON: '📁',
  CHECK_ICON: '✅',
  FAIL_ICON: '❌',
  TIP_ICON: '💡',
  WARNING_ICON: '⚠️',
  PACKAGE_ICON: '📂',
} as const;

export const ELEMENT_IDS = {
  MAIN_GRAPH: 'main-graph',
  QUALITY_CONTENT: 'quality-content',
  FRONTEND_QUALITY_CONTENT: 'frontend-quality-content',
  METRICS_CONTENT: 'metrics-content',
  CODE_EXPLORER_CONTENT: 'code-explorer-content',
  RELATIONS_CONTENT: 'relations-content',
  ASSETS_CONTENT: 'assets-content',
  EXPLORER_CONTENT: 'explorer-content',
  API_ENDPOINTS_CONTENT: 'api-endpoints-content',
  ARCHITECTURE_CONTENT: 'architecture-content',
  COMPLEXITY_CHART: 'complexity-chart',
  DISTRIBUTION_CHART: 'distribution-chart',
  TREE_SEARCH: 'tree-search',
  TREE_CONTENT: 'tree-content',
  PANEL_DIAGRAM: 'panel-diagram',
  PANEL_SOURCE: 'panel-source',
  PANEL_CALLS: 'panel-calls',
  CTX_CONTENT: 'ctx-content',
  ENDPOINTS_LIST_CONTAINER: 'endpoints-list-container',
  RELATIONS_LIST_CONTAINER: 'relations-list-container',
  UML_CONTAINER: 'uml-container',
  UML_PRE: 'uml-pre',
  COPY_CODE_BTN: 'copy-code-btn',
  PROJECT_SELECTOR: 'projectSelector',
  LOADING: 'loading',
  TOAST_CONTAINER: 'toastContainer',
} as const;

export const LAYOUT = {
  // Display / slice limits
  MAX_ENDPOINTS_DISPLAY: 50,
  MAX_RELATIONS_DISPLAY: 100,
  MAX_VIOLATIONS_DISPLAY: 50,
  MAX_ISSUES_DISPLAY: 10,
  MAX_FIELDS_DISPLAY: 20,
  MAX_METHODS_DISPLAY: 20,
  MAX_IMPORT_DEPS: 8,

  // Truncation lengths
  TRUNCATE_PATH: 30,
  TRUNCATE_TEXT: 25,
  TRUNCATE_EVIDENCE: 40,
  TRUNCATE_DESCRIPTION: 40,

  // Timings
  INIT_DELAY_MS: 100,
  MERMAID_RENDER_DELAY_MS: 100,
  CHART_RESIZE_DELAY_MS: 50,

  // Cache
  SOURCE_CODE_CACHE_SIZE: 50,

  // Force Graph params
  FORCE_REPULSION: 300,
  FORCE_EDGE_LENGTH: 90,
  FORCE_GRAVITY: 0.08,
  FORCE_FRICTION: 0.6,
  FORCE_EMPHASIS_WIDTH: 4,
  FORCE_EMPHASIS_BLUR: 15,
  FORCE_LABEL_SIZE: 11,
  FORCE_NODE_BASE_INTERNAL: 20,
  FORCE_NODE_BASE_EXTERNAL: 15,
  FORCE_NODE_CAP_DEGREE: 50,
  FORCE_NODE_SIZE_INTERNAL: 20,
  FORCE_NODE_SIZE_EXTERNAL: 10,
  FORCE_LINK_OPACITY: 0.3,
  FORCE_LINK_WIDTH_FACTOR: 0.1,
  FORCE_LINK_MAX_WIDTH: 4,
  FORCE_LINK_CURVENESS: 0.2,
  FORCE_SYMBOL_SIZE_NONE: 0,
  FORCE_SYMBOL_SIZE_ARROW: 6,

  // Zoom
  ZOOM_IN_FACTOR: 1.2,
  ZOOM_OUT_FACTOR: 0.8,
  ZOOM_ANIMATION_MS: 300,

  // Export
  PIXEL_RATIO: 2,
  EXPORT_BG: '#0b0f19',

  // CSS values used inline
  PADDING_40: '40px',
  PADDING_20: '20px',
  PADDING_16: '16px',
  PADDING_14: '14px',
  PADDING_12: '12px',
  PADDING_10: '10px',
  PADDING_8: '8px',
  PADDING_6: '6px',
  PADDING_4: '4px',
  PADDING_3_10: '3px 10px',
  PADDING_4_10: '4px 10px',
  PADDING_2_4: '2px 4px',
  PADDING_2_6: '2px 6px',
  PADDING_6_10: '6px 10px',
  PADDING_8_12: '8px 12px',
  PADDING_40_20: '40px 20px',
  PADDING_12_16: '12px 16px',
  MARGIN_BOTTOM_6: '6px',
  MARGIN_BOTTOM_8: '8px',
  MARGIN_BOTTOM_12: '12px',
  MARGIN_BOTTOM_24: '24px',
  MARGIN_TOP_2: '2px',
  MARGIN_TOP_4: '4px',
  MARGIN_TOP_6: '6px',
  MARGIN_TOP_8: '8px',
  MARGIN_LEFT_24: '24px',
  MARGIN_RIGHT_12: '12px',
  MARGIN_8_0: '8px 0',
  BORDER_RADIUS_3: '3px',
  BORDER_RADIUS_4: '4px',
  BORDER_RADIUS_6: '6px',
  BORDER_RADIUS_8: '8px',
  BORDER_RADIUS_10: '10px',
  BORDER_RADIUS_12: '12px',
  FONT_SIZE_10: '10px',
  FONT_SIZE_11: '11px',
  FONT_SIZE_12: '12px',
  FONT_SIZE_13: '13px',
  FONT_SIZE_14: '14px',
  FONT_SIZE_16: '16px',
  FONT_WEIGHT_500: '500',
  FONT_WEIGHT_600: '600',
  FONT_WEIGHT_700: '700',
  FONT_FAMILY_MONO: "'Courier New', monospace",
  FONT_FAMILY_MONO_ALT: 'monospace',
  LINE_HEIGHT_1_5: '1.5',
  GAP_6: '6px',
  GAP_8: '8px',
  GAP_10: '10px',
  MAX_WIDTH_200: '200px',
  GRID_MIN_240: '240px',
  GRID_MIN_220: '220px',
  BORDER_LEFT_3: '3px',
  BORDER_LEFT_4: '4px',
} as const;
